name = "thesis-lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ThesisLean", "Challenge", "Solution"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "58d6e790080f66348d86c115a1e00ab9b6343f70"

[[lean_lib]]
name = "ThesisLean"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
